checks:
  python:
    typecheck_maybe_no_member: true
    duplicate_code: true
    code_rating: true
    classes_valid_slots: true
    basic_missing_reversed_argument: true
tools:
  pylint:
    python_version: 3
    config_file: '.pylintrc'
build:
  environment:
    python: 3.7.1
  nodes:
    tests: true
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: pylint-run
            use_website_config: true
      project_setup:
        before:
          - command: pip3 install -r requirements.txt
            on_node: 1
            idle_timeout: 10
          - command: pip3 install -r test/requirements_for_test.txt
            on_node: 1
            idle_timeout: 10
          - command: python3 test/test_application.py&
            background: true
            on_node: 1
            idle_timeout: 10
    test:
      commands:
        - command: 'pytest --cov-report term --cov=apifuzzer --durations=10 --show-capture=stdout -vv -rP test'
          on_node: 1
          idle_timeout: 10
filter:
  excluded_paths:
    - "test/"
