checks:
    python:
        typecheck_maybe_no_member: true
        duplicate_code: true
        code_rating: true
        classes_valid_slots: true
        basic_missing_reversed_argument: true

build:
    environment:
        python: 3.4.6, 3.6.3, 3.7.1
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - py-scrutinizer-run
                    - command: pylint-run
                        use_website_config: true
        test:
            project_setup:
                before:
                    - command: pip3 install -r test/requirements_for_test.txt && python3 test/test_application.py
                      background: true
                commands:
                    - command: pip3 install -r test/requirements_for_test.txt && cd test && pytest --durations=10 --show-capture=stdout -v -rP test.py
filter:
    excluded_paths:
        - "test/"
